<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => null,
        'name' => 'cakephp/app',
        'dev' => true,
    ),
    'versions' => array(
        'aura/installer-default' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'composer-installer',
            'install_path' => __DIR__ . '/../aura/installer-default',
            'aliases' => array(),
            'reference' => '52f8de3670cc1ef45a916f40f732937436d028c8',
            'dev_requirement' => false,
        ),
        'aura/intl' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'aura-package',
            'install_path' => __DIR__ . '/../aura/intl',
            'aliases' => array(),
            'reference' => 'c5fe620167550ad6fa77dd3570fba2efc77a2a21',
            'dev_requirement' => false,
        ),
        'cakephp/app' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => null,
            'dev_requirement' => false,
        ),
        'cakephp/bake' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../cakephp/bake',
            'aliases' => array(),
            'reference' => '7940937c23fb186f7454074cf5f4b4e601e92d92',
            'dev_requirement' => true,
        ),
        'cakephp/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.14',
            ),
        ),
        'cakephp/cakephp' => array(
            'pretty_version' => '3.1.14',
            'version' => '3.1.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/cakephp',
            'aliases' => array(),
            'reference' => '88e0ff225324d746a2772bbfad128e858692a668',
            'dev_requirement' => false,
        ),
        'cakephp/collection' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.14',
            ),
        ),
        'cakephp/core' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.14',
            ),
        ),
        'cakephp/database' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.14',
            ),
        ),
        'cakephp/datasource' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.14',
            ),
        ),
        'cakephp/event' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.14',
            ),
        ),
        'cakephp/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.14',
            ),
        ),
        'cakephp/i18n' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.14',
            ),
        ),
        'cakephp/log' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.14',
            ),
        ),
        'cakephp/orm' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.14',
            ),
        ),
        'cakephp/plugin-installer' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'composer-installer',
            'install_path' => __DIR__ . '/../cakephp/plugin-installer',
            'aliases' => array(),
            'reference' => '3be2ea116603341b196592053e973f4abe71e8b2',
            'dev_requirement' => false,
        ),
        'cakephp/utility' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.14',
            ),
        ),
        'cakephp/validation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.14',
            ),
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'reference' => '3ce240142f6d59b808dd65c1f52f7a1c252e6cfd',
            'dev_requirement' => false,
        ),
        'composer/composer' => array(
            'pretty_version' => '1.10.27',
            'version' => '1.10.27.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./composer',
            'aliases' => array(),
            'reference' => 'f8f49191eec76f039b466aa1f161406fe43aff50',
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '1.7.2',
            'version' => '1.7.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'reference' => '647490bbcaf7fc4891c58f47b825eb99d19c377a',
            'dev_requirement' => false,
        ),
        'composer/spdx-licenses' => array(
            'pretty_version' => '1.5.8',
            'version' => '1.5.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./spdx-licenses',
            'aliases' => array(),
            'reference' => '560bdcf8deb88ae5d611c80a2de8ea9d0358cc0a',
            'dev_requirement' => false,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '1.4.6',
            'version' => '1.4.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'reference' => 'f27e06cd9675801df441b3656569b328e04aa37c',
            'dev_requirement' => false,
        ),
        'dnoegel/php-xdg-base-dir' => array(
            'pretty_version' => 'v0.1.1',
            'version' => '0.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dnoegel/php-xdg-base-dir',
            'aliases' => array(),
            'reference' => '8f8a6e48c5ecb0f991c2fdcf5f154a47d85f9ffd',
            'dev_requirement' => true,
        ),
        'ircmaxell/password-compat' => array(
            'pretty_version' => 'v1.0.4',
            'version' => '1.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ircmaxell/password-compat',
            'aliases' => array(),
            'reference' => '5c5cde8822a69545767f7c7f3058cb15ff84614c',
            'dev_requirement' => false,
        ),
        'jakub-onderka/php-console-color' => array(
            'pretty_version' => 'v0.2',
            'version' => '0.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakub-onderka/php-console-color',
            'aliases' => array(),
            'reference' => 'd5deaecff52a0d61ccb613bb3804088da0307191',
            'dev_requirement' => true,
        ),
        'jakub-onderka/php-console-highlighter' => array(
            'pretty_version' => 'v0.4',
            'version' => '0.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakub-onderka/php-console-highlighter',
            'aliases' => array(),
            'reference' => '9f7a229a69d52506914b4bc61bfdb199d90c5547',
            'dev_requirement' => true,
        ),
        'jdorn/sql-formatter' => array(
            'pretty_version' => 'v1.2.17',
            'version' => '1.2.17.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jdorn/sql-formatter',
            'aliases' => array(),
            'reference' => '64990d96e0959dff8e059dfcdc1af130728d92bc',
            'dev_requirement' => false,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => 'v5.2.13',
            'version' => '5.2.13.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'reference' => 'fbbe7e5d79f618997bc3332a6f49246036c45793',
            'dev_requirement' => false,
        ),
        'mobiledetect/mobiledetectlib' => array(
            'pretty_version' => '2.8.45',
            'version' => '2.8.45.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mobiledetect/mobiledetectlib',
            'aliases' => array(),
            'reference' => '96aaebcf4f50d3d2692ab81d2c5132e425bca266',
            'dev_requirement' => false,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => '1.13.0',
            'version' => '1.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(),
            'reference' => '5cb6e71055f7b0b57956b73d324cc4de31278f42',
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v2.1.1',
            'version' => '2.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'reference' => '4dd659edadffdc2143e4753df655d866dbfeedf0',
            'dev_requirement' => true,
        ),
        'psr/log' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'fe0936ee26643249e916849d48e3a51d5f5e278b',
            'dev_requirement' => false,
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.9.12',
            'version' => '0.9.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'reference' => '90da7f37568aee36b116a030c5f99c915267edd4',
            'dev_requirement' => true,
        ),
        'robmorgan/phinx' => array(
            'pretty_version' => 'v0.5.3',
            'version' => '0.5.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../robmorgan/phinx',
            'aliases' => array(),
            'reference' => '4e7fee7792f4bf3dbf55ee29001850ba26c86a88',
            'dev_requirement' => false,
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.10.2',
            'version' => '1.10.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'reference' => '9bb7db07b5d66d90f6ebf542f09fc67d800e5259',
            'dev_requirement' => false,
        ),
        'seld/phar-utils' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/phar-utils',
            'aliases' => array(),
            'reference' => 'ea2f4014f163c1be4c601b9b7bd6af81ba8d701c',
            'dev_requirement' => false,
        ),
        'symfony/config' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'reference' => '7dd5f5040dc04c118d057fb5886563963eb70011',
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => 'cbcf4b5e233af15cd2bbd50dee1ccc9b7927dc12',
            'dev_requirement' => false,
        ),
        'symfony/debug' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/debug',
            'aliases' => array(),
            'reference' => '74251c8d50dd3be7c4ce0c7b862497cdc641a5d0',
            'dev_requirement' => false,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'reference' => '7ae46872dad09dffb7fe1e93a0937097339d0080',
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'reference' => '1444eac52273e345d9b95129bf914639305a9ba4',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => 'aed596913b70fae57be53d86faa2e9ef85a2297b',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => 'b5f7b932ee6fa802fc792eabd77c4c88084517ce',
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'reference' => 'c3591a09c78639822b0b290d44edb69bf9f05dc8',
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'reference' => '91abb1e39d14fb7773d25de9c711949ea8502ac1',
            'dev_requirement' => true,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => '02c1859112aa779d9ab394ae4f3381911d84052b',
            'dev_requirement' => false,
        ),
    ),
);
