version: '3'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      # - ./:/var/www
    #  - .:/var/www/html
     - ./html:/test/example.com/htdocs
    #  - ./app:/test/example.com/app
    ports:
      - ${WEB_PORT}:80
    # command: ["sh", "-c", "chmod -R 755 /var/www && apache2-foreground"]

  db:
    # image: mysql:8.0
    # command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    # environment:
    #   - MYSQL_DATABASE=${DB_NAME}
    #   - MYSQL_USER=${DB_USER}
    #   - MYSQL_PASSWORD=${DB_PASS}
    #   - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    # ports:
    #   - ${DB_PORT}:3306
    # restart: always

    image: mariadb:5.5.64
    volumes:
      - ./mariadb/data:/var/lib/mysql
      # - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    ports:
      - ${DB_PORT}:3306
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASS}
    links:
      - db
    ports:
      - ${PMA_PORT}:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions