version: '3'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
     - .:/test/example.com
    ports:
      - ${WEB_PORT}:80

  db:
    image: mariadb:5.5.64
    volumes:
      # - ./mariadb/data:/var/lib/mysql
      - mysql_data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/mariadb.conf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    ports:
      - ${DB_PORT}:3306
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASS}
    links:
      - db
    ports:
      - ${PMA_PORT}:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

volumes:
  mysql_data: